### ISSUE TITLE
About reproduction accuracy

### ISSUE THREAD

**Issue by Sheldon04** [zysxmu/DDTB#2]
Hello! I trained the model several times by your code and settings with EDSR, but only got PSNR 28.37 on Set14, which is lower than the 28.39 in your paper. Could you please explain how to reproduce the accuracy? Thanks!

**Comment by zysxmu** [comment]
Well, actually, I think the 0.02 is negligible. In my view, maybe >0.05 is a non-ignorable gap. 
So, I do really consider that you have reproduced this already.
BTW, you can try more for a better result. In fact, in my experiments, I got better results (>28.39) occasionally.
