### ISSUE TITLE
Question on the reported table

### ISSUE THREAD

**Issue by YouCaiJun98** [zysxmu/DDTB#3]
Hello dear authors, I'm quite confused about the results you reported in table 1. and table 2. in the original paper.
The 3-bit quantized EDSR-PAMS performs worse than the 2-bit quantized one, and so does RDN-PAMS. It's kind of weird since the models quantized by the other comparing methods don't exhibit such characteristics.  I wonder if you could share your opinion regarding this with me, thanks :)

**Comment by YouCaiJun98** [comment]
I acquired your [released article](https://arxiv.org/abs/2203.03844) on arxiv, which is versioned 3.

**Comment by zysxmu** [comment]
According to our experiments, it is true.

We attribute that to the failure of initialization of the clipping value of the activation. In fact, when performing 3-bit quantization, the clipping value of the activation will explode which leads to poor results.

**Comment by YouCaiJun98** [comment]
Thanks for your quick reply : )
What puzzles me is that such phenomenon only happens under the 3-bit case (while the more aggressively quantized 2-bit case can better retain the performance). I'll further look into it.

**Comment by zysxmu** [comment]
Have a nice trip!
