### ISSUE TITLE
How to calculate model size(params) in paper

### ISSUE THREAD

**Issue by jimmy9704** [zysxmu/DDTB#4]
Hello, I am very impressed with your paper :)
How did you calculate the params in your paper?
Full precision EDSR is 1.52M and 2-bit EDSR is 0.41M.
So I guess 1.52 / ? = 0.41 
And what number will go in "?"

**Comment by zysxmu** [comment]
Oh, the first and last layers in the model retain the full-precision. You should take it into consideration.

**Comment by jimmy9704** [comment]
thanks!
